#!/bin/bash

bam=$1
params_density_buckets=$2
params_density_window_width=75
params_density_step_size=20
params_chrom_sizes=$3
sample_id=$4

bam2bed -d \
    < "${bam}" \
    | cut -f1-6 \
    | awk '{ if( $6=="+" ){ s=$2; e=$2+1 } else { s=$3-1; e=$3 } print $1 "\t" s "\t" e "\tid\t" 1 }' \
    | sort-bed - \
    > sample.bed
  
  unstarch "${params_density_buckets}" \
    | bedmap --faster --echo --count --delim "\t" - sample.bed \
    | awk -v OFS="\t" \
        -v binI=${params_density_step_size} \
        -v win="${params_density_window_width}" \
        'BEGIN{ halfBin=binI/2; shiftFactor=win-halfBin } { 
            print $1,$2+shiftFactor,$3-shiftFactor,"id",$4}' \
    | starch - \
    > "${name}"
    
  unstarch "${name}" \
    | awk -v binI="${params_density_step_size}" \
        -f "bedToWig.awk" > density.wig

  wigToBigWig -clip density.wig "${params_chrom_sizes}" ${sample_id}.density.bw
